version: "3"

services: 

    # Session storage
    redis:
        build: 
            context: _docker_/redis
            dockerfile: Dockerfile


    # Dev container
    dev:
        build: 
            context: . 
            dockerfile: _docker_/php-dev/Dockerfile
        volumes: 
            - ".:/app"
        env_file:
            - ".env"
        depends_on:
            - redis
            - db


    # Web client to access container 'redis'
    # When in production, should be removed
    redis-ui:
        image: marian/rebrow
        ports: 
            - "15001:5001"
        depends_on: 
            - redis

    db:
        build:
            context: .
            dockerfile: _docker_/mongo/Dockerfile
        restart: always
        ports:
        - "${DB_EXTERNAL_PORT}:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_HOST: ${MONGO_HOST}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

    # Client to access and inspect the DB
    # Should be removed when in production
    mongo-client:
        image: mongo-express:latest
        ports:
        - "${DB_UI_EXTERNAL_PORT}:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
        depends_on:
            - db
        
